{{- if .Values.cloudflareTunnel.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baseline.fullname" . }}-tunnel-credentials
  labels:
    {{- include "baseline.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials.json: {{ .Values.cloudflareTunnel.credentials | toJson | quote }}
{{- end }}
