{{- if .Values.cloudflare.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baseline.fullname" . }}-cloudflare
  labels:
    {{- include "baseline.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.cloudflare.apiToken | quote }}
{{- end }}
